name: TypeScript Compiler
on: [pull_request, push]
jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14.16
      uses: actions/setup-node@v2
      with:
        node-version: 14.16
    - name: yarn install
      run: yarn install
    - name: TypeScript Compiler
      uses: icrawl/action-tsc@v1